 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/securityproject
     username: root
     password:
     driven-class-name: com.mysql.jdbc.Driver
   jpa:
     hibernate:
       ddl-auto: create-drop
     show-sql: true
     properties :
        hibernate:
          format_sql: true
     database: Mysql
     database-platform: org.hibernate.dialect.MySQL8Dialect

 logging:
         config: classpath:log4j2.xml
         system: LOGBACK






